import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MdEmail } from "react-icons/md";
import { BiPhone } from "react-icons/bi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* footer */}
        <div className="flex flex-col gap-4 items-center justify-center text-white bg-orange-800 min-h-20 w-screen p-5">
          <h3>Ezeani Chukwudi {new Date().getFullYear()}</h3>
          <h5 className="flex items-center gap-2 text-sm">
            <MdEmail />
            {"concord_chucks2@yahoo.com"}
          </h5>
          <h5 className="flex items-center gap-2 text-sm">
            <BiPhone />
            {"+2348067268692"}
          </h5>
        </div>
      </body>
    </html>
  );
}
